# Generated by Django 4.0.5 on 2022-07-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_upvotedreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='upvotedreview',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='upvotedreview',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
