# Generated by Django 4.0.5 on 2022-08-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='coop_term_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
