# Generated by Django 4.0.5 on 2022-07-16 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0002_savedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_wage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_relocation_stipend', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('monthly_misc_stipends', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('term_signing_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('year_worked', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('term_worked', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Winter', 'Winter')], max_length=6)),
                ('coop_term_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('program', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
    ]
