# Generated by Django 4.0.5 on 2022-07-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_salary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='year_worked',
            field=models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022),
        ),
    ]
