# Generated by Django 4.0.5 on 2022-07-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewquestion',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='upvotedinterviewquestion',
            old_name='interview_question_id',
            new_name='interview_question',
        ),
        migrations.RenameField(
            model_name='upvotedinterviewquestion',
            old_name='user_id',
            new_name='user',
        ),
    ]
