# Generated by Django 4.0.5 on 2022-07-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_savedjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='savedjob',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='savedjob',
            old_name='user_id',
            new_name='user',
        ),
    ]
