# Generated by Django 4.0.5 on 2022-08-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_industry'),
        ('job', '0003_alter_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('company', 'name')},
        ),
    ]
